// app/layout.tsx or app/layout.js
import type { Metadata } from "next";
import "./globals.css";

// 1. Import the font
import { Poppins } from "next/font/google";

// 2. Configure the font
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "600", "700"], // You can include more weights if needed
  display: "swap",
});

export const metadata: Metadata = {
  title: "Ekramul Portfolio",
  description: "Generated by Ekramul",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* 3. Apply the font className to body or html */}
      <body className={poppins.className}>
        <div>{children}</div>
      </body>
    </html>
  );
}
